global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "my-project"

rule_files:
  - "alert.rules"
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
scrape_configs:
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "prometheus"
    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"

    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080

  - job_name: "node-exporter"
    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - "tasks.node-exporter"
        type: "A"
        port: 9100
