version: "3.7"

services:
  prom:
    image: prom/prometheus
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000

volumes:
  prometheus_data: {}

networks:
  default:
    name: metrics-network
